services:
  server:
    image: go-fast-cdn
    build: .
    ports:
      - "6262:6262"
    volumes:
      - uploads:/app/uploads
      - db_data:/app/db_data
    container_name: go-fast-cdn
volumes:
  db_data:
  uploads:
